
spring:
  main:
    web-application-type: reactive
  config:
    import: optional:file:./env.properties
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: ${CONFIG_SERVICE_NAME}
          uri: ${CONFIG_SERVICE_URI}
          predicates:
            - Path=/api/config/**
          filters: AuthenticationFilter
        - id: ${IDENTITY_SERVICE_NAME}
          uri: ${IDENTITY_SERVICE_URI}
          predicates:
            - Path=/api/identity/**,
              /api/module/**
          filters: AuthenticationFilter

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE}

logging:
  level:
    root: INFO
    org.spring.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE


