
spring:
  config:
    import: optional:file:./env.properties
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: ${IDENTITY_SERVICE_NAME}
          uri: lb://${IDENTITY_SERVICE_NAME}
          predicates:
            - Path=/api/identity/**
          filters: AuthenticationFilter

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE}

logging:
  level:
    root: INFO
    org.spring.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE


