spring:
  config:
    import: optional:file:./env.properties
  datasource:
    url: ${IDENTITY_DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  application:
    name: ${IDENTITY_SERVICE_NAME}

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE}

