spring:
  config:
    import: optional:file:./env.properties
  datasource:
    url: ${IDENTITY_DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  application:
    name: ${CONFIG_SERVICE_NAME}

server:
  port: 0

JWT_SECRET: D6pHbCIpA3dZvajlllOEwM91yXzBboYl6FXUJRGOaISjN7ZWyUiz7S1ofd7eHZXS